### ISSUE TITLE
Update UML diagram

### ISSUE THREAD

**Issue by Inge505** [sloththedev/cos214-project#14]

**Comment by Inge505** [comment]
Change weapon hierarchy
Add platoon functions to unit
Update Theatre of War

**Comment by sloththedev** [comment]
Unit and Country state function name change
`request()` -> `requestState()`

**Comment by GT-GillesTeuwen** [comment]
Alliances:
 Added name:string

Battle:
 Changed constructor to Battle(TheatreOfWar * air, TheatreOfWar * land, Area * area);

AirBranch:
 Added string getBranch()

Branch:
 Added string getBranch()

LandBranch:
  Added string getBranch()

SeaBranch:
 Deleted Class

Country:
 Added alliances:Alliances*
 Added Alliances* getAlliances()

Area:
 Changed constructor to Area::Area(string name, int index, int colour,bool factories)
 Changed marchIn() to Battle *Area::marchIn(Unit *unit)
 Changed marchOut() to bool Area::marchOut(Area* whereTo)
 Added bool Area::requestResources(int type)
 Added -bool Area::checkIfBattleHappens()

TheatreOfWar:
 Added many methods

TransportRoute:
 Added Area* TransportRoute::getFrom()
 Added Area* TransportRoute::getTo(){

PTFactory, WTFactory, GTFactory:
 Added Transport *makeTypeTransport();

Unit:
 Added split()
 Added getBranch()
 Added getAllaince()



Sorry

**Comment by Inge505** [comment]
Add Player, User, CPU hierarchy

**Comment by GT-GillesTeuwen** [comment]
Alliances:
  Added colour:int
  Added constructor Alliances(string name,int colour);
  Added getColour()

Country:
  Added ~Country
  Added getAlliances():Alliances*
  Added getName():string

Area:
  Added country:Country*

Map:
  Added allCountries: vector<Country*>
  Added addCountry(country:Country*)

Platoon:
  Added ~Platoon()

Human:
  Added print()
  Added ~Human()

Unit:
  Added setCountry(country:Country*)
  Added getCountry():Country*
  Added ~Unit()
